apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: frontend
            path: terraform-project/trivy
            namespace: trivy
          # - name: backend
          #   path: apps/backend
          # - name: auth
          #   path: apps/auth
  template:
    metadata:
      name: '{{name}}'
    namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/your-repo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
