apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
