# name: trivy-security-scanning
# on: push

# permissions:
#   security-events: write # To upload sarif files

# jobs:
#   chart-test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
#         with:
#           fetch-depth: 0

#       - name: Set up Helm
#         uses: azure/setup-helm@f382f75448129b3be48f8121b9857be18d815a82 # tag=v3.4
#         with:
#           version: v3.6.3

#       - name: Set up python
#         uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # tag=v4.3.0
#         with:
#           python-version: 3.7

#       - name: Run Trivy vulnerability scanner in IaC mode
#         uses: aquasecurity/trivy-action@9ab158e8597f3b310480b9a69402b419bc03dbd5 # tag=0.8.0
#         with:
#           scan-type: 'config'
#           hide-progress: false
#           format: 'sarif'
#           scan-ref: 'charts/sample-helm-devsecops'
#           output: 'trivy-results.sarif'
#           exit-code: '1'
#           ignore-unfixed: true

#       - name: Upload Trivy scan results to GitHub Security tab
#         uses: github/codeql-action/upload-sarif@312e093a1892bd801f026f1090904ee8e460b9b6 # v2.1.34
#         with:
#           sarif_file: 'trivy-results.sarif'

# name: Trivy Helm Chart Scan (On Merge to Main)

# on:
#   push:
#     branches:
#       - main
# permissions:
#   security-events: write # Required to upload SARIF files to the GitHub Security tab
# jobs:
#   trivy-helm-scan:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Run Trivy on checked-in Helm chart
#         uses: aquasecurity/trivy-action@v0.8.0
#         with:
#           scan-type: config
#           scan-ref: charts/trivy              # 👈 scan the folder you pulled into
#           format: sarif
#           output: trivy-results.sarif
#           exit-code: 1                        # ❌ fail CI if issues found
#           ignore-unfixed: true

#       - name: Upload Trivy scan results to GitHub Security tab
#         uses: github/codeql-action/upload-sarif@v2
#         with:
#           sarif_file: trivy-results.sarif

name: Trivy Helm Chart Scan (PR)
on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform-project/**'  # Only run if files under charts/ change
permissions:
  security-events: write
jobs:
  trivy-helm-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Find changed chart directories
        id: changes
        run: |
          # Find all chart directories that changed in this PR
          echo "::group::Detect changed charts"
          CHANGED_DIRS=$(git diff --name-only origin/main | grep '^charts/' | cut -d/ -f1-2 | sort -u)
          echo "$CHANGED_DIRS"
          echo "dirs=$CHANGED_DIRS" >> $GITHUB_OUTPUT
          echo "::endgroup::"
      - name: Scan all changed charts with Trivy
        uses: aquasecurity/trivy-action@v0.8.0
        with:
          scan-type: config
          scan-ref: charts/your-chart-name-here  # replace or loop for each chart dir
          format: sarif
          output: trivy-results.sarif
          exit-code: 1
          ignore-unfixed: true
      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif